# Generated by Django 4.1.7 on 2023-03-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.AddIndex(
            model_name='csvfile',
            index=models.Index(fields=['created_at'], name='idx_csv_file_created_at'),
        ),
    ]
